# Generated by Django 2.0 on 2019-02-27 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(help_text='关于这条记录的评论信息')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.IntegerField(choices=[(1, '参数有错误'), (2, '服务器不能处理当前状况')])),
                ('error_name', models.CharField(help_text='错误的名称', max_length=20)),
                ('error_help', models.CharField(help_text='关于这个错误的说明', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='errorlogmodel',
            name='error',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='error.ErrorModel'),
        ),
        migrations.AddField(
            model_name='errorlogmodel',
            name='user_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
