# Generated by Django 2.0 on 2019-03-07 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('error', '0005_auto_20190227_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('URL', models.TextField(help_text='原始的访问URL')),
                ('post_data', models.TextField(help_text='被转化为文本的post的数据')),
                ('get_data', models.TextField(help_text='被转化为文本的get的数据')),
                ('header_data', models.TextField(help_text='被转化为文本的header的数据')),
                ('cookie_data', models.TextField(help_text='被转化为文本的cookie的数据')),
                ('user_obj', models.ForeignKey(help_text='出现异常的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='errorlogmodel',
            name='error',
        ),
        migrations.RemoveField(
            model_name='errorlogmodel',
            name='user_obj',
        ),
        migrations.DeleteModel(
            name='ErrorLogModel',
        ),
        migrations.DeleteModel(
            name='ErrorModel',
        ),
    ]
